# Generated by Django 5.1.2 on 2024-10-28 13:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='age',
        ),
        migrations.RemoveField(
            model_name='information',
            name='phone',
        ),
        migrations.AddField(
            model_name='information',
            name='Input',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
