# Generated by Django 5.1.2 on 2024-10-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_information_age_remove_information_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='Input',
            field=models.TextField(default=None),
        ),
    ]
