# Generated by Django 5.1.2 on 2024-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_information_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Input',
            new_name='Task',
        ),
        migrations.RemoveField(
            model_name='information',
            name='email',
        ),
        migrations.RemoveField(
            model_name='information',
            name='name',
        ),
        migrations.AddField(
            model_name='information',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
