# Generated by Django 5.1.2 on 2024-10-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_input_information_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='Task',
            new_name='task',
        ),
    ]
