# Generated by Django 5.1.2 on 2024-10-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_date_information_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.TextField(default=None),
        ),
    ]
