# Generated by Django 5.1.2 on 2024-11-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accesories_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_value', max_length=20, null=True)),
                ('qauntity', models.IntegerField(default=0, null=True)),
                ('maintenance', models.DateField(default='2024-01-01', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='members_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_value', max_length=20, null=True)),
                ('phone_no', models.IntegerField(default=0, null=True)),
                ('email', models.EmailField(default='default_value', max_length=254, null=True)),
                ('duration', models.CharField(default='default_value', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_value', max_length=20, null=True)),
                ('phone_no', models.IntegerField(default='default_value', null=True)),
                ('email', models.EmailField(default='default_value', max_length=254, null=True)),
                ('payscale', models.IntegerField(default='default_value', null=True)),
                ('join_date', models.DateField(default='2024-01-01', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transactions_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='default_value', max_length=30, null=True)),
                ('data', models.DateField(default='2024-01-01', null=True)),
            ],
        ),
    ]
