# Generated by Django 5.1.2 on 2024-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_members_model_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_model',
            name='join_date',
            field=models.DateField(default='2024-01-01', null=True),
        ),
    ]
