# Generated by Django 5.1.2 on 2024-12-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_members_model_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_model',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
