# Generated by Django 5.1.2 on 2024-12-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_members_model_join_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_model',
            name='trainer',
        ),
    ]
