# Generated by Django 5.1.2 on 2024-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_members_model_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesories_model',
            name='maintenance',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accesories_model',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='members_model',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='members_model',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='members_model',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainers_model',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trainers_model',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trainers_model',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trainers_model',
            name='payscale',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='trainers_model',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transactions_model',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
