# Generated by Django 5.1.2 on 2024-12-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_data_transactions_model_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members_model',
            name='duration',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
