# Generated by Django 5.1.2 on 2024-12-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_alter_members_model_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='members_model',
            name='trainer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
