# Generated by Django 5.1.2 on 2024-12-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_remove_members_model_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members_model',
            name='join_date',
        ),
    ]
