# Generated by Django 5.1.2 on 2024-12-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_alter_accesories_model_maintenance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions_model',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='members_model',
            name='duration',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
